name: Test

on: [push]

jobs:
  test:
    runs-on: [ self-hosted, Linux, X64, mortar-runner ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Check formatting
        run: ./gradlew ktlintCheck

      - name: Run unit test
        run: ./gradlew test

      - name: Build
        run: ./gradlew clean build -x test
